version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5440:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=crudbasic
